### ISSUE TITLE
Completed Assignment 6 to practice Rmd - Publishing papers

### ISSUE THREAD

**Issue by liliana-krp** [liliana-krp/Assignment-6#1]
In this assignment, I learned how to manipulate a R Markdown file that changed the YAML, in-text citations, and small code call to the references to all have it automatically generated for you pretty easily. 

Things I struggled with:
- how to not come back with error messages about small issues RE headers/margins that did not seem to impact of the final outcome
- navigating error messages and not proper outputs for the in-text citations and references

Things I found handy:
- pretty much all of this! I am tempted to try to use this for my final bibliographies and reports as it seems to streamline the process

**Comment by liliana-krp** [comment]
- [x] Ready to assign to @mdscheuerell whenever accepts invitation

**Comment by mdscheuerell** [comment]
Some thoughts from me regarding your struggles mentioned above:

> how to not come back with error messages about small issues RE headers/margins that did not seem to impact of the final outcome

I would need to see the error message(s) before I could help with this, but it doesn't sound like it was impactful.

> navigating error messages and not proper outputs for the in-text citations and references

Again, what were the error messages? Check back [here](https://fish549.github.io/website/lectures/week_04/lec_11_getting_help.html) about creating a reprex.

To complete this assignment, you should go back and review the material on references and citations in Markdown docs [here](https://fish549.github.io/website/lectures/week_07/lec_21_markdown_2.html#Literature_cited). Decide which of the two options you're going to use for inserting citations and formatting the references section and then follow those instructions. Two immediate issues I see:
1) Independent of which option you choose, you'll need to replace/revise the placeholders I left in the template for in-text citations.
2) You are trying to call an R function outside of a code block [here](https://github.com/liliana-krp/Assignment-6/blob/d298f627b9affc374a51e147aa7545dd68f7dd31/hw_06.Rmd#L134). You may want to review the info [here](https://fish549.github.io/website/lectures/week_07/intro_rmarkdown.html#Writing_code).

**Comment by liliana-krp** [comment]
Hi Mark,

Sorry for not providing more context through a reprex. **I will leave two here now after this comment, for the two issues I left above.**

In regards to your comment on completing the assignment thus far, I reviewed the resources for the Markdown docs. I did the first option, a Zotero bib export (which is included in my repo, and looks good from my end WRT in-text citations and calling them). For your two immediate issues:
1. At least with my current version, I have definitely replaced the placeholders for in-text citations by auto-generating them through call keys. Hopefully the version you saw also had that as that's what I thought it looked like!
2. When I include the *below bit of code*, it fails and I cannot produce a pdf. **My most recent commits include *(A)* the HW 6 Rmd with this bit of code included to share that it cannot run as is and *(B)* HW 6 Rmd (and pdf) without the code chunks but just the code line alone**

` ```{r} write.bibtex(file = "references.bib")``` `

**Comment by mdscheuerell** [comment]
> At least with my current version, I have definitely replaced the placeholders for in-text citations by auto-generating them through call keys. Hopefully the version you saw also had that as that's what I thought it looked like!

Yes, what you had/have there for in-text citations (eg, `[@broman_data_2018]`) works for Option 1, but...

> When I include the below bit of code, it fails and I cannot produce a pdf. My most recent commits include (A) the HW 6 Rmd with this bit of code included to share that it cannot run as is and (B) HW 6 Rmd (and pdf) without the code chunks but just the code line alone
>
> ```{r} write.bibtex(file = "references.bib")```

It's because you're trying to use a mix of Options 1 & 2. Right now your in-text citations follow Option 1. Your YAML is set up properly and the requisite `.bib` and `.csl` files are in place, so the rendered doc looks good. For Option 2, you would need the `{knitcitations}` package, but I don't see where that package is being loaded or otherwise called explicitly with something like `knitcitations::write.bibtex()` (see info [here](https://fish549.github.io/website/lectures/week_07/lec_21_markdown_2.html#Initial_setup)).

**Comment by mdscheuerell** [comment]
At this point I will accept what you've done here for this assignment.

**Comment by liliana-krp** [comment]
Dear @mdscheuerell,

Thank you for closing the issue, and I just wanted to follow up quickly on my solution:

I see now my issue with calling write.bibtex() when I was trying to do Option 1! I believe my most recent commit of hw_06 pdf and Rmd should now reflect the final report format and code, respectively.

Thank you so much for your help on this assignment, particularly considering it is past the deadline. I truly appreciate it.
